services:
  app:
    image: nightknighto/spring-petclinic
    environment:
      MYSQL_URL: jdbc:mysql://database/petclinic
      SPRING_PROFILES_ACTIVE: mysql
    healthcheck:
      test:
        - CMD-SHELL
        - wget -O - localhost:8080
      timeout: 30s
      interval: 30s
      retries: 3
      start_period: 0s
    networks:
      - clinic
    ports:
      - 8080
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 15s
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: petclinic
    networks:
      - clinic
    volumes:
      - db_vol_sql:/var/lib/mysql

networks:
  clinic:

volumes:
  db_vol_sql:
