apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
      type: api
  template:
    metadata:
      labels:
        app: spring-petclinic
        type: api
    spec:
      containers:
      - name: spring-petclinic-api
        image: nightknighto/spring-petclinic
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: spring-petclinic-api-config
          
