apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-db
spec:
  selector:
    matchLabels:
      app: spring-petclinic
      type: db
  template:
    metadata:
      labels:
        app: spring-petclinic
        type: db
    spec:
      containers:
      - name: spring-petclinic-db
        image: mysql:8.4
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: spring-petclinic-db-config
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
        
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: spring-petclinic-db-pvc

