apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-petclinic-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: spring-petclinic-db
  hostPath:
    path: /data/spring-petclinic-db