apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-petclinic-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: spring-petclinic-db
