services:
  database:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    networks:
      - clinic
    volumes:
      - db_vol_psql:/var/lib/postgresql/data

  app:
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://database/petclinic

volumes:
  db_vol_psql:
